FROM node:20.20.0-slim

# 作業ディレクトリの設定
WORKDIR /app

# フロントエンド依存関係のコピー
COPY frontend/package*.json ./
RUN npm install

# フロントエンドソースのコピー
COPY frontend/ ./

# フロントエンドのビルド
RUN npm run build

# フロントエンドポートの公開
EXPOSE 3000

# フロントエンドをフォアグラウンドで起動する
CMD ["npm", "start"]